export const perfis = {
  "viajante_perdido": {
    usuario: "viajante_perdido",
    nome: "Sobrevivente da Cidade",
    avatar: "/imagens/viajanteperdido.perfil.jpg",
    corAvatar: "#c9a84c",
    bio: "Preso nesta cidade há meses. Ainda procurando respostas. Ajudo quem posso. #FROM",
    link: "",
    seguindo: true,
    contadorPosts: 12,
    contadorSeguidores: 234,
    contadorSeguindo: 89,
    postagens: [],
  },
  "Boyd Stevens": {
    usuario: "@xerifeboyd",
    nome: "Boyd Stevens",
    avatar: "/imagens/boyd.jpg",
    corAvatar: "#c9a84c",
    bio: "Xerife da cidade de FROM. Protejo cada alma até encontrarmos a saída. A esperança nunca morre.",
    link: "",
    seguindo: true,
    contadorPosts: 42,
    contadorSeguidores: 1523,
    contadorSeguindo: 156,
    postagens: [1],
  },
  "Tabitha": {
    usuario: "@tabithavisoes",
    nome: "Tabitha",
    avatar: "/imagens/Tabitha.jpg",
    corAvatar: "#8e44ad",
    bio: "Vejo padrões onde outros veem caos. Os símbolos nas árvores não são uma maldição. São um mapa.",
    link: "",
    seguindo: false,
    contadorPosts: 28,
    contadorSeguidores: 891,
    contadorSeguindo: 204,
    postagens: [2],
  },
  "Victor": {
    usuario: "@vivedafloresta",
    nome: "Victor",
    avatar: "/imagens/victor.jpg",
    corAvatar: "#27ae60",
    bio: "Sobrevivi mais tempo que todos. Conheço cada árvore, cada caverna, cada segredo.",
    link: "",
    seguindo: false,
    contadorPosts: 15,
    contadorSeguidores: 567,
    contadorSeguindo: 12,
    postagens: [3],
  },
  "Jade": {
    usuario: "@jadetalisma",
    nome: "Jade",
    avatar: "/imagens/jade.jpg",
    corAvatar: "#3498db",
    bio: "Programador preso em FROM. Descobri que os talismãs são fractais. Matemática, não magia.",
    link: "",
    seguindo: false,
    contadorPosts: 67,
    contadorSeguidores: 2104,
    contadorSeguindo: 89,
    postagens: [4],
  },
  "Sara": {
    usuario: "@saravozes",
    nome: "Sara",
    avatar: "/imagens/sara.jpg",
    corAvatar: "#e74c3c",
    bio: "As vozes me guiam. Nem todo mundo entende, mas estou aqui para ajudar. O menino é a chave.",
    link: "",
    seguindo: false,
    contadorPosts: 9,
    contadorSeguidores: 345,
    contadorSeguindo: 67,
    postagens: [5],
  },
  "Ethan": {
    usuario: "@ethanboy",
    nome: "Ethan",
    avatar: "/imagens/ethan.perfil.png",
    corAvatar: "#16a085",
    bio: "Filho de Tabitha. Vejo coisas que os adultos não conseguem. O menino é a chave, eles dizem.",
    link: "",
    seguindo: false,
    contadorPosts: 3,
    contadorSeguidores: 89,
    contadorSeguindo: 12,
    postagens: [],
  },
  "Kenny": {
    usuario: "@kennycolonia",
    nome: "Kenny",
    avatar: "/imagens/kenny.perfil.png",
    corAvatar: "#2c3e50",
    bio: "Vivo na Colônia com Donna. Aprendi que sobrevivência é questão de união.",
    link: "",
    seguindo: false,
    contadorPosts: 7,
    contadorSeguidores: 156,
    contadorSeguindo: 34,
    postagens: [],
  },
  "Fatima": {
    usuario: "@fatimaesperanca",
    nome: "Fatima",
    avatar: "/imagens/farima.perfil.png",
    corAvatar: "#e91e63",
    bio: "Mesmo neste lugar sombrio, encontro motivos para sorrir. A esperança é o que nos mantém vivos.",
    link: "",
    seguindo: false,
    contadorPosts: 5,
    contadorSeguidores: 201,
    contadorSeguindo: 78,
    postagens: [],
  },
  "Ellis": {
    usuario: "@ellisfilhodoboyd",
    nome: "Ellis",
    avatar: "/imagens/ellis.perfil.jpg",
    corAvatar: "#f39c12",
    bio: "Filho do xerife Boyd. Acredito que podemos construir algo novo aqui dentro.",
    link: "",
    seguindo: false,
    contadorPosts: 8,
    contadorSeguidores: 189,
    contadorSeguindo: 45,
    postagens: [],
  },
  "Randall": {
    usuario: "@randallconflitos",
    nome: "Randall",
    avatar: "/imagens/randall.perfil.png",
    corAvatar: "#d35400",
    bio: "Não confio em ninguém. A cidade já me mostrou o suficiente. Cada um por si.",
    link: "",
    seguindo: false,
    contadorPosts: 2,
    contadorSeguidores: 67,
    contadorSeguindo: 23,
    postagens: [],
  },
  "Donna": {
    usuario: "@donalider",
    nome: "Donna",
    avatar: "/imagens/dona.jpg",
    corAvatar: "#e67e22",
    bio: "Líder da Colônia. Todos comem, todos dormem, todos sobrevivem. Enquanto eu estiver aqui, ninguém morre.",
    link: "",
    seguindo: false,
    contadorPosts: 31,
    contadorSeguidores: 1234,
    contadorSeguindo: 45,
    postagens: [6],
  },
}
